### ISSUE TITLE
Statement

### ISSUE THREAD

**Issue by janetaquino** [ga-students/dsiplusoutcomes#3]
I am a data scientist working on some projects that involve working with python. I have started projects that emphasize in Numpy and Pandas as well as matplot. I continue to learn and keep applying new skills to the projects I am working on.

I used to work in the field of education as a math tutor. Here I learned how to manage time communicate information well to students in different perspectives as well as keeping a great communication with parents.

**Comment by nicoleump** [comment]
Thanks Janet for submitting. Please submit it to your local market repo here: https://github.com/ga-students/la-outcomes-homework
