### ISSUE TITLE
Moises Salazar outcome HW

### ISSUE THREAD

**Issue by Moisessalazar77** [ga-students/dsiplusoutcomes#5]
[moisesresume.pdf](https://github.com/ga-students/dsiplusoutcomes/files/1782620/moisesresume.pdf)

Hello 
Attached to this email is a copy of my resume.
Three organization that had pick my interest are:

-google.
-Stash.
-ComLinkData.

Kind regards

**Comment by nicoleump** [comment]
Please submit this to your local market repo here: https://github.com/ga-students/new-york-outcomes-homework
